### PR TITLE
feat: CountableSet constructor with initial map

### PR DESCRIPTION
**Pull request by kovsu**
related to #2986

### CODE REVIEW

**Comment by antfu** [comment]
Can you add a test to it? The main branch seems to be fine

**Comment by kovsu** [comment]
@antfu I don't know why the ci's test all passed. but I get the test failed locally you can see here. :)
截屏2023-09-26 14 18 01

the [falied test file](https://github.com/unocss/unocss/blob/main/test/countable-set.test.ts) is here.

**Comment by antfu** [comment]
Did you build first?

**Comment by kovsu** [comment]
oh my bad T.T, sry.

**Pull request closed without merging**
