### PR TITLE
fix(vite): generate css files for specified rollupOptions in library mode

### LINKED ISSUE #2192: doesn't generate css files because it doesn't respect rollupOptions when vite builds in library mode
### UnoCSS version

0.49.4

### Describe the bug

Unocss doesn't generate css files because it doesn't respect rollupOptions when vite builds in library mode

for a library vite build configuration, eg. in vite.config.ts:

```javascript
export default defineConfig({
	build: {
		lib: {
			entry: resolve(__dirname, "index.ts"),
			name: "theme",
		},
		rollupOptions: {
			output: [
				{
					dir: "dist/es",
					format: "es",
					entryFileNames: "[name].mjs",
					assetFileNames: "assets/theme.css",
					preserveModules: true,
					preserveModulesRoot: resolve(__dirname, "../"),
					sourcemap: false,
				},
				{
					dir: "dist/cjs",
					format: "cjs",
					entryFileNames: "[name].cjs",
					assetFileNames: "assets/theme.css",
					preserveModules: true,
					preserveModulesRoot: resolve(__dirname, "../"),
					sourcemap: false,
				},
				{
					dir: "dist/umd",
					format: "umd",
					entryFileNames: "index.js",
					name: "Theme",
					sourcemap: false,
				},
				{
					dir: "dist/iife",
					format: "iife",
					entryFileNames: "index.js",
					name: "Theme",
					sourcemap: false,
				},
			],
		},
		outDir: resolve(__dirname, "dist"),
		emptyOutDir: true,
		cssCodeSplit: true,
	},
	plugins: [Unocss({ mode: "global", include: [/\.ts$/] })],
});
```

Problem lies in unocss->packages->vite->modes->global->build.ts, here is the problem code:
```javascript
const cssPost = cssPostPlugins.get(options.dir)
if (!cssPost) {
  this.warn('[unocss] failed to find vite:css-post plugin. It might be an internal bug of UnoCSS')
  return null
}
```
Problem is that options.dir is "dir/es", "dir/cjs", etc., as defined in rollupOptions.  Whereas cssPostPlugins is initialized as
```javascript
async configResolved(config) {
        const distDir = resolve(config.root, config.build.outDir)
        cssPostPlugins.set(distDir, config.plugins.find(i => i.name === 'vite:css-post'))
        cssPlugins.set(distDir, config.plugins.find(i => i.name === 'vite:css'))
        await ready
},
```
this `distDir` is absolute path to `outDir`: home/xxx/project/dist.  it will never match with options.dir

As you can see, cssPost will always be null, and code will always return null without proceeding.

Proposed solution is to add entries in cssPostPlugins and cssPlugins for each rolloutOptions `dir` property.  I tested this solution, and it works.

I can make a pr if you want this solution.  Although I don't understand why it's done this way, I mean, vite:css-post plugin can be found, why have to go through a map to look for it.

### Reproduction

will provide if required

### System Info

vite 4.1.1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by agufagit**
Closes #2192 

I don't know how to write unit test for this change, but I did test it manually.

### CODE REVIEW

**Comment by agufagit** [comment]
@antfu can you review this?

**Comment by antfu** [comment]
I am not against it, but I am also not very sure what's the case it's solving. Can you write a fixture test for it? Thanks

**Comment by antfu** [comment]
You may refer to: https://github.com/unocss/unocss/blob/c4438351f1e0e6915bad121a5462b74c698a4b40/test/fixtures.test.ts#L49-L83

**Comment by agufagit** [comment]
fixture test is done.

This case might be rare.  I was writing a UI components library https://ui.agufa.tech for Vue and Svelte based on Unocss last July.  There was a treeshaking problem with either Nuxt or Sveltekit (I don't remember which one exactly) with a single .js file, so I had to use rollupOptions per-module to generate js files.

That said, I still want this to work because I'm going to do a new project in Qwik, and I'm transforming this UI library to qwik syntax.  As qwik is relatively new, I want to keep using what was safely working because you never know when a new framework might blow up.

The failed checks are not related to my changes.  It's vue-cli4 test case that's failing, it also failed for other pull requests as I just checked, including the one just committed to main branch.  This error might be related to node versions, it's reproducible with node 18, but works with node 16 on my computer.  I'm not sure why it failed node 14 and 16 here, might be test environment change, might be an internal bug of vue-cli4

**Pull request closed without merging**
