### PR TITLE
chore: IDEA eslint compatibility

### PR DESCRIPTION
**Pull request by sudongyuer**
#1566

### CODE REVIEW

**Comment by antfu** [comment]
I am not sure. I think it's better to have IDEA fix it instead of reverting the version on our side

**Comment by userquin** [comment]
@antfu will be fixed in 2022.2.3 so there is no need to update here: https://youtrack.jetbrains.com/issue/WEB-57089

**Comment by sudongyuer** [comment]
> @antfu will be fixed in 2022.2.3 so there is no need to update here: https://youtrack.jetbrains.com/issue/WEB-57089
> 
> EDIT: it is 2 versions from current, this will take time... and it is a bad experience since we lose dx

+1

**Comment by userquin** [comment]
@antfu IntelliJ 2022.2.2 released and seems the error is gone, so we can revert this.

**Pull request merged**
