### PR TITLE
feat: allow to return generated css inline

### PR DESCRIPTION
**Pull request by fehnomenal**
See https://github.com/unocss/unocss/pull/2098#issuecomment-1401844999

Vite seems to need `?inline` at the resolved id.
- [ ] docs?
- [ ] test
- [ ] get this actually to work lol

### CODE REVIEW

**Comment by lisonge** [comment]
@fehnomenal 

hello, why the module `virtual:uno.css?inline` still has sideEffects ?

when `vite build`, why the `default export` of `virtual:uno.css?inline` is `''` ?

**Comment by fehnomenal** [comment]
I'm sorry, I really cannot answer your questions. I guess the exported value depends on the uno config and the mode.

**Comment by lisonge** [comment]
> exported value depends on the uno config

I didn't find it, where is it ?

**Comment by lisonge** [comment]
about it, you can see <https://github.com/unocss/unocss/issues/2533>

**Pull request closed without merging**
