### PR TITLE
feat(playground): add reset option

### PR DESCRIPTION
**Pull request by sudongyuer**
Just open the link below for more details👇

https://jam.dev/c/965392e2-5e57-45ce-ae0c-11940a6a894e

image

### CODE REVIEW

**Comment by sudongyuer** [comment]
> Just open the link below for more details👇
> 
> https://jam.dev/c/965392e2-5e57-45ce-ae0c-11940a6a894e
> 
> image

By the way,I found that no one in UNOCSS/CLI is maintaining it. Can I join the team to maintain @unocss/cli ? Please give me this opportunity ~

**Review by antfu — APPROVED** [review]
It would be better to:

- Add confirmation before doing so
- Move the button to the left-most, and use `i-carbon-erase` icon otherwise it's could be a bit confusing to recognize as "refresh" or "undo"

**Comment by sudongyuer** [comment]
> It would be better to:
> 
> * Add confirmation before doing so
> * Move the button to the left-most, and use `i-carbon-erase` icon otherwise it's could be a bit confusing to recognize as "refresh" or "undo"

Ok got it

**Comment by sudongyuer** [comment]
Now it looks like this
image

**Pull request merged**
