### PR TITLE
feat: add defaultUnocssConfig to webpack plugin and unocss vscode extension

### LINKED ISSUE #1032: [Vscode extension] the preset config is prerequisite
I want to use Unocss Vscode extension in my unocss+vite+react project, it doesn't work until i config presets, and i didn't find this prerequisite for using Unocss Vscode extension. if it isn't a bug, maybe we should list this prerequisite in the README.md under packages/vscode?

# addtional info
it doesn't work
```js
//vite.config.ts
import { defineConfig } from 'vite'
import Unocss from 'unocss/vite'
import react from '@vitejs/plugin-react'
import tsconfigPaths from 'vite-tsconfig-paths'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    Unocss({}),
    tsconfigPaths(),
  ],
})

```
it works
```js
//vite.config.ts
import { defineConfig } from 'vite'
import Unocss from 'unocss/vite'
import { presetUno } from 'unocss'
import react from '@vitejs/plugin-react'
import tsconfigPaths from 'vite-tsconfig-paths'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    Unocss({
      presets: [presetUno()],
    }),
    tsconfigPaths(),
  ],
})

```
Please let me know if you need more information.

### PR DESCRIPTION
**Pull request by TrickyPi**
close #1032 

also make webpack plugin use [@unocss/preset-uno](https://github.com/unocss/unocss/tree/main/packages/preset-uno) as default preset.

### CODE REVIEW

**Review by antfu — CHANGES_REQUESTED** [review]
Well, it's intentional to have `@unocss/vite` and `@unocss/webpack` preset irrelevant so higher integrations that provide their own presets could reuse them if they want. I am ok to have the default theme on the extension but not the webpack plugin. Thanks

**Comment by TrickyPi** [comment]
The default presets will be overridden by custom configuration, like this describition https://github.com/unocss/unocss/blob/main/README.md?plain=1#L166, so i think there will be no issues about integration(maybe i'm wrong).
perhaps we can export a function like [UnocssVitePlugin](https://github.com/unocss/unocss/blob/main/packages/unocss/src/vite.ts#L8) for webpack user,

**Comment by antfu** [comment]
I don't want to force download the presets for those who don't need them. Maybe we could have `unocss/webpack` which binds the default preset and ask `@unocss/webpack` as peerDeps

**Comment by TrickyPi** [comment]
if we ask @unocss/webpack as peerDeps, maybe we need list this info in instruction.  Could we add instruction about how to use unocss on  webpack  to  [README.md](https://github.com/unocss/unocss/blob/main/README.md)?

**Comment by antfu** [comment]
Sure, I would handle the docs part

**Comment by TrickyPi** [comment]
Thanks for your commits.

**Pull request closed without merging**
