### PR TITLE
fix(transformer-directive): get raw string in directive, support slash & hash

### LINKED ISSUE #3784: `transformer-directives` transforms opacities incorrectly
### UnoCSS version

v0.60.0

### Describe the bug

```css
* {
  --uno: bg-black/5
}
```

Is transformed into

```css
* {
  --un-bg-opacity:1;
  background-color:rgb(0 0 0 / var(--un-bg-opacity));
}
```

### Reproduction

In the UnoCSS Playground:

1. add `transformerDirectives()` to `transformers` in _Config_ panel
2. add `* { --uno: bg-black/5 }` to  _Custom CSS_ panel

And you will see the background is totally black.

### System Info

Edge, Windows

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by zyyv**
Since the ast generated by `csstree` does not meet this scenario, I will manually rearrange the ast. close #3784

### CODE REVIEW

**Comment by antfu** [comment]
I guess https://github.com/unocss/unocss/issues/3788 also falls into a similar situation. And maybe `:` as well?

**Comment by antfu** [comment]
I don't know if we could retrieve the `raw` content of the attribute value.

**Comment by zyyv** [comment]
> I guess #3788 also falls into a similar situation. And maybe `:` as well?

For this case, `--uno: text-red:5;` There are two `:`, obviously this is not a correct css syntax.

I'll update the test case see the output.

**Comment by zyyv** [comment]
If the node type was `Declaration`, those children node never has `Raw` type content. fixed #3788 
(The result of manually adjusting ast is hopefully a good solution. 😂)

**Comment by antfu** [comment]
We could actually slice the code to get the raw string :)

**Review by antfu — APPROVED** [review]

**Comment by hooray** [comment]
I want to know if this is a bug. Do I have to write it like this in the future  ?

`--at-apply: hover:bg-stone-1 dark:hover:bg-stone-9;` -> `--at-apply: "hover:bg-stone-1" "dark:hover:bg-stone-9";`

**Comment by zyyv** [comment]
> I want to know if this is a bug. Do I have to write it like this in the future ?
> 
> `--at-apply: hover:bg-stone-1 dark:hover:bg-stone-9;` -> `--at-apply: "hover:bg-stone-1" "dark:hover:bg-stone-9";`

When multiple `:` appear without quotes, `css-tree` will parse incorrectly. At the same time, we should also follow the css writing rules. 
```diff
{ 
  prop: value;
}

{
- --at-apply: hover:bg-stone-1 dark:hover:bg-stone-9;
+ --at-apply: 'hover:bg-stone-1 dark:hover:bg-stone-9';
}
```

**Pull request merged**
