### PR TITLE
docs: scrollbar-hide community presets

### PR DESCRIPTION
**Pull request by reslear**

### CODE REVIEW

**Comment by zyyv** [comment]
@reslear  I think this preset has too few preset rules and is more for customization.
I think you can send a PR to this community preset https://github.com/action-hong/unocss-preset-scrollbar.

/cc @action-hong

**Comment by reslear** [comment]
No, because many people do not need scrollbar customization, but only visual hiding. also my tailwind css plugin https://github.com/reslear/tailwind-scrollbar-hide most polular.

Example tailwind plugins: 

scrollbar: https://www.npmjs.com/package/tailwind-scrollbar **54k** downloads
scrollbar hide: https://www.npmjs.com/package/tailwind-scrollbar-hide **65k** downloads

**Review by antfu — CHANGES_REQUESTED** [review]
Please move it to the end of the list, then I am ok to have it. Thanks

**Comment by reslear** [comment]
hi @antfu thanks, done, have a good day  :)

**Pull request merged**
