### PR TITLE
doc: add warning to AttributifyAttributes ts usage.

### PR DESCRIPTION
**Pull request by Xwil**
https://github.com/unocss/unocss/issues/1702

### CODE REVIEW

**Comment by antfu** [comment]
I would like to know the more specific number of the expected slow down, like 2.4x slower or just 10% etc.?

**Comment by Xwil** [comment]
It's like 0.1s to 3~5s, both of VSCode and WebStorm.

**Comment by Flower-F** [comment]
> I would like to know the more specific number of the expected slow down, like 2.4x slower or just 10% etc.?

I test it in my Windows laptop, and the TS inference time will be 2~3s slower.

**Comment by Flower-F** [comment]
> I would like to know the more specific number of the expected slow down, like 2.4x slower or just 10% etc.?

Can we give an alternate to the user, such as

```tsx
import type { AttributifyAttributes } from '@unocss/preset-attributify';

declare module "react" {
  interface HTMLAttributes<T> extends Partial<Record<string, any>> { }
}
```

I fount it doesn't  slow down the TypeScript inference, but of course it might cause some other errors when using an non-existent property.

**Comment by Xwil** [comment]
> > I would like to know the more specific number of the expected slow down, like 2.4x slower or just 10% etc.?
> 
> Can we give an alternate to the user, such as
> 
> ```tsx
> import type { AttributifyAttributes } from '@unocss/preset-attributify';
> 
> declare module "react" {
>   interface HTMLAttributes<T> extends Partial<Record<string, any>> { }
> }
> ```
> 
> I fount it doesn't slow down the TypeScript inference, but of course it might cause some other errors when using an non-existent property.

What about [Typescript Language Service Plugin](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin) ?

**Pull request closed without merging**
