### PR TITLE
chore: inherit baseTheme by default

### PR DESCRIPTION
**Pull request by Simon-He95**
related: #3214

I think this way will be more friendly and convenient to use that Merge initialized themes through custom attributes.

### CODE REVIEW

**Comment by zyyv** [comment]
This is not a good idea and it prevents me from clearing the uno theme.

```ts
extendTheme: () => ({}), // Not work.
```

**Comment by Simon-He95** [comment]
> This is not a good idea and it prevents me from clearing the uno theme.
> 
> ```ts
> extendTheme: () => ({}), // Not work.
> ```

I want to know why you need to clear the default uno theme. Shouldn't it be used as the base theme and then extended?

**Comment by zyyv** [comment]
We should keep `extendTheme` simple and have no side effects.

**Comment by Simon-He95** [comment]
> We should keep `extendTheme` simple and have no side effects. And clear the theme just a example.

I personally think tailwind's merge is more reasonable, just like a component library. I hope to use its components, but for example, the color is not what I expected, so I overwrite it instead of writing a custom style. , causing the styles of its default component library to no longer take effect, and it is necessary to merge its default styles in customized places.

**Comment by zyyv** [comment]
I think what you mean is more appropriate using the `theme` option, `extendTheme` means you have full control over the theme, different from tailwind.

**Comment by Simon-He95** [comment]
Oh, I see, I thought they were both doing the same thing

**Pull request closed without merging**
