### PR TITLE
fix(preset-typography): move `font-family` css of `code` in default preflights

### LINKED ISSUE #3104: [preset-typography] `--un-prose-font-mono` is missing from generated CSS
### UnoCSS version

v0.55.7

### Describe the bug

While customizing `fontFamily.mono` with `theme` in `defineConfig`, `--un-prose-font-mono` is missing from the generated `prose`:

```css
.prose{
  color: var(--un-prose-body);
  max-width: 65ch;
}
```

... causing the monospaced font not to be applied for elements (e.g., `<code />`) using this CSS variable.

It seems that `--un-prose-font-mono` is only generated with the `^${selectorName}-([-\\w]+)$` rule (e.g., `prose-red`):

https://github.com/unocss/unocss/blob/e0982104319178b44c8a40a9f0add1d4a16eb523/packages/preset-typography/src/index.ts#L89-L123

### Reproduction

A minimal reproduction is available [on the playground](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAOBaALOgPgCgopRJZEUMAXAUwA8a8G5CTSyYB7EOggBR8AZggCucGgEpYvOgC4ADAEYATAGYBU4AHoefYqV3gIhsicrI06ekxZwomAE7ckddpy5yCAOmeu6WT4lNU1tPW8OY0gzcmh4K1pGZlxWRxc3dIDsJzoQD05gfX4-DLpS7NyQIIUVDS1dYtidE2Jo0yIgA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jACr9IpKAEMwAC0FURDGAFVcESgF84WKBBBwA5F00BjOnWNIkGAB6RY6bDK4AbeJhz4iJYKQAFMjCtKp0AFxwANoqjBoQgQCU5NRhjCxsnDx8-MmpcTASUrIKeUkAukJwMPIYIBhRIah6xDAAYjIgwO78TVQtcCDEEFHGRN3mcADKMrh0cACy08bVqNrVG0jaSbZAA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA) with UnoCSS v0.55.7:

I customized the monospaced font in the theme to `'Comic Sans MS'`:

```js
export default defineConfig({
  presets: [presetUno(), presetAttributify(), presetTypography()],
  theme: {
    fontFamily: {
      mono: 'Comic Sans MS',
    },
  },
})
```

As you can see, Comic Sans is only applied to the `div.prose.prose-red` but not `div.prose`.

Screenshot 2023-09-11 at 11 27 44

### System Info

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by zyyv**
close #3104, close #3105

### CODE REVIEW

**Comment by zyyv** [comment]
Thanks @sumimakito, and I optimized this behavior in another way. Please review it.

**Comment by zyyv** [comment]
@jacob-8 Sorry ping, can you help me check the test errors on [actions](https://github.com/unocss/unocss/actions/runs/6168090101/job/16740181762)?

**Comment by jacob-8** [comment]
> @jacob-8 Sorry ping, can you help me check the test errors on [actions](https://github.com/unocss/unocss/actions/runs/6168090101/job/16740181762)?

If the prose styles changed, you should be able to run `pnpm test:update` then just inspect the differences. Let me know if there are other issues.

**Comment by zyyv** [comment]
> > @jacob-8 Sorry ping, can you help me check the test errors on [actions](https://github.com/unocss/unocss/actions/runs/6168090101/job/16740181762)?
> 
> @zyyv if the prose styles changed, you should be able to run `pnpm test:update` then just inspect the differences. Let me know if there are other issues.

Thanks, but I had run `pnpm test:update`, but the expect code not update. I change it manually.

**Review by sumimakito — APPROVED** [review]
LGTM

**Comment by jacob-8** [comment]
> Thanks, but I had run `pnpm test:update`, but the expect code not update. I change it manually.

Ok, I looked at it and it was because the svelte-scoped unit tests were operating off the built typography package and not the source code. If you build and then run the tests locally again you'll get what you were expecting the first time.

**Review by antfu — APPROVED** [review]

**Pull request merged**
