### PR TITLE
feat(preset-typography): compatibility mode(#2051)

### PR DESCRIPTION
**Pull request by lixiang810**
See #2051

### CODE REVIEW

**Comment by zyyv** [comment]
Hi, it seems to not support for `not-prose` with use compatibility mode.
[Playground](https://deploy-preview-2064--unocss.netlify.app/play/?html=DwEwlgbgBADgTgewM4FMB8AoKVgzQgOwFoQUBbAQwJCgHaowCkAXK5uqAMwFcAbXgJ5QAxtxYIyYAF4UARrxTAA9Hiw4YI3hSRIAvACICCZkXjIU%2B-MVKVqHRizYce-IaPGSZ8xSszLwEGhAA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGABV%2BkUlACGYABaCqIhQFVcESgF84WKBBBwA5F2MS6dW0iQYAHpFjps6rgA28Jg4%2BEQkwKQAFMioUIH0AFxwANpUqCm2Elx0MNYAtPEBGLbkiHBSAdDJtrRotnCmALpUTbJ0WtAw2TB0ybGodtm5BR1dPbY1MJ4w%2BQGkcNMes9DquKQYcJ0AbhhQiUuz0%2BoBrqimsvqMfanpcqIwRhBRAJSywvKMLGycPHz8r3e9wUylUGm0AIGqAAkFJwOpeBxgAFgDB%2BABZCCYZJsLgYO6mN53K4wSTSGJ3VB0CQnDDJACMADoAExA1ASNC4GpaVhgPoAen59BAjI6-LOg0JshahKQQA&options=N4XyA)

**Comment by lixiang810** [comment]
> Hi, it seems to not support for not-prose with use compatibility mode.

This is expected and is explained in the jsdoc and README.

**Comment by zyyv** [comment]
@lixiang810 I modified the code a bit and removed `:is`. I think we should drop all pseudo-classes when using compatibility mode, what do you think?

**Comment by lixiang810** [comment]
> @lixiang810 I modified the code a bit and removed `:is`. I think we should drop all pseudo-classes when using compatibility mode, what do you think?

Nice, I forgot it. The `:is()` selector is also unavaliable before Chrome 88.

**Comment by zyyv** [comment]
> > @lixiang810 I modified the code a bit and removed `:is`. I think we should drop all pseudo-classes when using compatibility mode, what do you think?
> 
> Nice, I forgot it. The `:is()` selector is also unavaliable before Chrome 88.

Let me check it again, it seems that the wrong code was i changed.😅

**Comment by antfu** [comment]
I am a bit hesitant about the name. `compatibility` is a relevant term, anything could be incompatible if their browsers are old enough. While browser list is probably too heavy for us, I think we could have an object instead:

```ts
compatibility: {
  noColonWhere: true,
  noColonIs: true
}
```

**Comment by lixiang810** [comment]
> ```typescript
> compatibility: {
>   noColonWhere: true,
>   noColonIs: true
> }
> ```

The compatibility between `:where()` and `:is()` is the same. Browsers that do not support `:where()` also do not support `:is()`, and vice versa. It seems that it is unnecessary for these two pseudo-classes.

**Comment by antfu** [comment]
> The compatibility of :where() and :is() is the same. Browsers that do not support :where() also do not support :is(), and vice versa. It seems that it is unnecessary for these two pseudo-classes.

This statement is only true in the context of the current existing browsers you are aware of. This may not always be the case, as you mentioned the exception. Users could also use a custom browser engine or anything, that does not always support them at the same time. Also in the future, there could be `:foo` `:bar` or anything. Having them in a single options is not practical.

**Comment by lixiang810** [comment]
Let's make a compromise: use these in the configuration and keep the original, cleaner options in the code.

**Comment by lixiang810** [comment]
OK. Now we have a fine-grained control.

**Review by zyyv — APPROVED** [review]

**Pull request merged**
