### PR TITLE
feat(autocomplete): support custom shorthands

### PR DESCRIPTION
**Pull request by chizukicn**
This PR will support custom shorthands on autocomplete.

```
import { defineConfig } from 'unocss'

export default defineConfig({
  autocomplete: {
    shorthands: {
      size: ['xs', 'sm', 'md', 'lg', 'xl', '2xl', '3xl', '4xl', '5xl', '6xl', 'full'],
    },
  },
})


```

### CODE REVIEW

**Comment by antfu** [comment]
I am not sure if I understand. Can you explain a bit what's this is trying to do?

**Comment by chizukicn** [comment]
> I am not sure if I understand. Can you explain a bit what's this is trying to do?

I think since autocomplete can customize extractors and templates, shorthands should also be able to extend and cover.

We can customize shorthands in preset. Although both theme and extractor can achieve this effect. But the theme may interfere with the runtime, and the extractor is too troublesome, which can be more of an option

**Comment by chizukicn** [comment]
eg:
image
image
We can easily customize autocomplete. @antfu

**Comment by chizukicn** [comment]
We can also customize the shorthand in the preset.
```ts
 export default {
    name: "preset-palette",
    autocomplete: {
      shorthands: {
        opacity: `(${Array.from({ length: 21 }, (_, i) => i * 5).join("|")})`
      }
    },
   rules:[
      [
        /^text-(\w+)\/(\d{1,2})$/,
        colorResolver("color"),
        {
          autocomplete: "text-$colors/<opacity>"
        }
      ],
  ]
}
```

Autocomplte:
image

**Comment by antfu** [comment]
OK now I see. Can you also add some documentation for this? Thanks.

**Comment by chizukicn** [comment]
> OK now I see. Can you also add some documentation for this? Thanks.

done~

**Review by antfu — APPROVED** [review]

**Pull request merged**
