### PR TITLE
fix(preset-web-fonts): fix creation of import URL for `bunny`

### PR DESCRIPTION
**Pull request by arunanshub**
Fixes the issue #2574.

### CODE REVIEW

**Comment by antfu** [comment]
Can you explain what is happening and why this fix would need? I guess it should be bunny's responsibility to align with Google's params?

**Comment by arunanshub** [comment]
> Can you explain what is happening and why this fix would need?

@antfu As highlighted in the linked issue, it simply fixes how the import URL is created. Earlier, it used to create the URL in a Google Fonts compatible manner. However, it seems like Bunny has decided to change how the fonts are loaded. Hence, the Google Fonts compatible 

> I guess it should be bunny's responsibility to align with Google's params?

It does work with Google's params **when executed in a browser**, but strangely refuses to work with UnoCSS when configured via `webFonts.provider`. It might also be related to caching:

https://github.com/unocss/unocss/blob/698a7e68d6dd2be0cc9e4fa7c335fd940776012c/packages/preset-web-fonts/src/index.ts#L58-L74

However I have yet to test out this hypothesis.

The important point here is that it only fails with **Bunny**, not Google. Hence if both are equally compatible with each other, and Google's loader works but Bunny's loader fails, it can be safely said there is something wrong with Bunny's loader.

**Comment by antfu** [comment]
It does sound like a bunny issue isn't it? I am still not very sure if we should keep the complexity on us.

**Comment by arunanshub** [comment]
> It does sound like a bunny issue isn't it? I am still not very sure if we should keep the complexity on us.

While the issue indeed lies with Bunny fonts, it is essential to note that the proposed fix is relatively straightforward and can be implemented within approximately 10 lines of code.

Plus, we should see Bunny as a separate font provider service and a [privacy-respecting competitor to Google Fonts](https://css-tricks.com/bunny-fonts/).

**Pull request merged**
