### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by Adam-Collier**
missing the `@` in the import 🙃

### CODE REVIEW

**Comment by chris-zhu** [comment]
Please refer to #1463

**Comment by Adam-Collier** [comment]
Ah gotcha, there may still need to be something done here though as in the astro config vs code is complaining with the message "Cannot find module 'unocss/astro' or its corresponding type declarations."

image

**Comment by chris-zhu** [comment]
> 啊，尽管在 astro 配置 vs 代码中的通知消息中出现了“找不到模块”，但这里可能仍然需要做一些事情。
> 
> 图片

Yes, i make a new PR at #1484, maybe can resolve it.

**Comment by Adam-Collier** [comment]
Great thanks 🙏

**Pull request closed without merging**
