### PR TITLE
fix(nuxt2): support nuxt2

### PR DESCRIPTION
**Pull request by poyoho**
fix: #1832

> autoimport unocss will generate the code 
>
> ```ts
> import 'uno.css'
> export default defineNuxtPlugin(() => {})
> ```
>
> but `defineNuxtPlugin` is not autoimport in pure nuxt2

### CODE REVIEW

**Comment by zyyv** [comment]
I test this example, but it doesn't work properly. So did this commit really solve the problem?

**Comment by poyoho** [comment]
@zyyv what the error do you meet?

**Comment by zyyv** [comment]
> @zyyv what the error do you meet?

image

**Comment by zyyv** [comment]
You can try to run it?

**Comment by poyoho** [comment]
I can run it. Can you provide the mini repo thanks 😀

**Comment by zyyv** [comment]
I'm just run https://github.com/unocss/unocss/tree/main/examples/nuxt2-webpack.
let me check it carefully again.

**Pull request merged**
