### PR TITLE
docs: make all examples easy to open in Stackblitz

### PR DESCRIPTION
**Pull request by jacob-8**
Links can be previewed at https://deploy-preview-2691--unocss.netlify.app/guide/#examples

## Examples with quirks:
- [astro-vue](https://stackblitz.com/fork/github/unocss/unocss/tree/stackblitz-examples/examples/astro-vue): has a warning: duplicate compile class name 'uno-06j1dt', please choose different class name from unocss:transformers:pre, src/components/Example.vue - looks like #2667 is tracking it so we can ignore it here.
- [remix](https://stackblitz.com/fork/github/unocss/unocss/tree/stackblitz-examples/examples/remix): prints out some deprecation notices and information on needed upgrades - probably an effortless update for @veritem if that seems helpful.

## Examples that don't work
I've not included these in the "Play Online" column for now, but the relevant contributors are welcome to update samples on their own PRs fixes are desired:
- [next](https://stackblitz.com/fork/github/unocss/unocss/tree/stackblitz-examples/examples/next): fails to load SWC binary for @next/swc-linux, this has been an [issue](https://github.com/stackblitz/core/issues/1904) for awhile. Stackblitz has a Next template from a few versions back that works in Stackblitz but if you remove their package-lock.json, set `next` version to most recent and re-install the error is back. I don't have the necessary Next experience to make decisions here. Any thoughts @Sickisonfire?
- [vite-svelte-postcss](https://stackblitz.com/fork/github/unocss/unocss/tree/stackblitz-examples/examples/vite-svelte-postcss): throws a Vite error: `end must be greater than start`, I know @sibbng is in process with the postcss stuff so I'm assuming this will resolve itself in time.
- [qwik](https://stackblitz.com/fork/github/unocss/unocss/tree/stackblitz-examples/examples/qwik): throws error: `Cannot find module 'undici'` - any thoughts, @vasilGerginski?
- [vite-elm](https://stackblitz.com/fork/github/unocss/unocss/tree/stackblitz-examples/examples/vite-elm): Broken but https://stackblitz.com/edit/elm-daisyui is an Elm + Stackblitz example that works fine. Any thoughts, @userquin?

## @antfu, I have a few remaining thoughts/questions:

- Is `/guide/#examples` the right location in the docs?
- The two `vue-cli` examples did not include a `pnpm-workspace.yaml` file. I "fixed" this but please undo if it was intentional.
- The majority of examples don't include `"type": "module"` in their `package.json` but I find it hard to believe that all of these are using commonjs. Looking at the first, Astro, their basic [template](https://astro.new/basics?on=stackblitz) includes  `"type": "module"`. Is this just an oversight that is a result of being placed within a monorepo that has `"type": "module"`? I think the examples should be updated to include `"type": "module"` as applicable so if people open in Stackblitz and then decide to download the project, things are set right for them to start their new project.

## TODO after review

- [ ] find-replace `stackblitz-examples/examples` to `main/examples` to update Stackblitz links to point to the proper branch

### CODE REVIEW

**Comment by userquin** [comment]
@jacob-8 linked stackblitz example is wrong, should be https://stackblitz.com/fork/github/unocss/unocss/tree/main/examples/vite-elm

I'll check it later, it seems some Elm dependencies broken, maybe Elm has changed:

<details>
<summary>Error</summary>

```shell
$ elm-tooling install
/home/projects/unocss-unocss-ua9umf/elm-tooling.json
  0% elm 0.19.1
  0% elm-format 0.8.4
  0% elm-json 0.2.8
  0% elm-test-rs 2.0.0
ERR! elm-format 0.8.4
ERR! elm-json 0.2.8
ERR! elm-test-rs 2.0.0
ERR! elm 0.19.1

4 errors

elm 0.19.1
    < https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
    > /home/.elm/elm-tooling/elm/0.19.1/elm
    
    socket hang up

elm-format 0.8.4
    < https://github.com/avh4/elm-format/releases/download/0.8.4/elm-format-0.8.4-linux-x64.tgz
    > /home/.elm/elm-tooling/elm-format/0.8.4/elm-format
    
    kill EPERM
    
    Maximum call stack size exceeded

elm-json 0.2.8
    < https://github.com/zwilias/elm-json/releases/download/v0.2.8/elm-json-v0.2.8-x86_64-unknown-linux-musl.tar.gz
    > /home/.elm/elm-tooling/elm-json/0.2.8/elm-json
    
    kill EPERM
    
    Maximum call stack size exceeded

elm-test-rs 2.0.0
    < https://github.com/mpizenberg/elm-test-rs/releases/download/v2.0/elm-test-rs_linux.tar.gz
    > /home/.elm/elm-tooling/elm-test-rs/2.0.0/elm-test-rs
    
    kill EPERM
    
    Maximum call stack size exceeded

```
</details>

**Comment by userquin** [comment]
@jacob-8 I've created https://stackblitz.com/edit/userquin-vite-elm-test-latest-unocss-8dmwhp from https://github.com/userquin/vite-elm-test-latest-unocss

In local works but still not working in StackBlitz

**Comment by jacob-8** [comment]
> In local works but still not working in StackBlitz

I don't know Elm so I'm not much help but I just wanted to ask in case it was an easy thing to make it work in Stackblitz. If it's not that's fine, people still have a good demo. If you figure it out down the road, just add the link. :)

**Comment by sibbng** [comment]
> [vite-svelte-postcss](https://stackblitz.com/fork/github/unocss/unocss/tree/main/examples/vite-svelte-postcss): throws a Vite error: end must be greater than start, I know @sibbng is in process with the postcss stuff so I'm assuming this will resolve itself in time.

It's a svelte compiler issue: https://github.com/sveltejs/svelte/issues/7518. For now we can remove `@screen md {}` from style block.

**Comment by iamhectorsosa** [comment]
@jacob-8 

> _[next](https://stackblitz.com/fork/github/unocss/unocss/tree/main/examples/next): fails to load SWC binary for @next/swc-linux, this has been an https://github.com/stackblitz/core/issues/1904 for awhile. Stackblitz has a Next template from a few versions back that works in Stackblitz but if you remove their package-lock.json, set next version to most recent and re-install the error is back. I don't have the necessary Next experience to make decisions here._

I also gave it a try but it doesn't work because Stackblitz has issues with [loading swr](https://nextjs.org/docs/messages/failed-loading-swc) which is Next rust-based compiler. Another possible solution here would be to add an example with a link to CodeSandBox which has support for it.

I noticed that the Next example is also based on the pages directory. App directory has become stable. I can open a PR if you guys are open for it.

**Comment by iamhectorsosa** [comment]
Note that the solution that Next posted in https://nextjs.org/docs/messages/failed-loading-swc isn't working with Stackblitz playgrounds based on https://github.com/vercel/next.js/discussions/30468

Therefore I would consider trying CodeSandbox in this case.

**Comment by jacob-8** [comment]
> I can open a PR if you guys are open for it.

Yes, please do @iamhectorsosa, with a CodeSandbox link. I don't know Next, but I will assume that just having one example using the app directory sufficient for learning's sake, even for those still using pages directory. Correct me if I'm wrong.

**Comment by iamhectorsosa** [comment]
I've drafted a PR -> https://github.com/unocss/unocss/pull/2724

I still have to update the Readme file but I'm shooting to replicate the Next + TailwindCSS starter to be Next + UnoCSS. Let me know what you think.

**Pull request merged**
