### PR TITLE
fix(generator): order in which css is generated

### PR DESCRIPTION
**Pull request by Simon-He95**
close: #3293

### CODE REVIEW

**Comment by chu121su12** [comment]
I think it's better to have the output sorted and use the layering utility and other variants to modify the priority/specificity.

Otherwise, looking at the updated css output, this should be tagged as breaking change.

**Comment by Simon-He95** [comment]
> I think it's better to have the output sorted and use the layering utility and other variants to modify the priority/specificity. [I think it's better to have the output sorted and use the layering utility and other variants to modify the priority/specificity.]
> 
> Otherwise, looking at the updated css output, this should be tagged as breaking change. [Otherwise, looking at the updated css output, this should be tagged as breaking change.]

The output results of sorting in alphabetical order are indeed relatively good-looking, but they ignore the issue of class order coverage, which may cause some hidden dangers of styles being overwritten and not taking effect. Is it possible to consider that some shortcuts are not layered separately, but retain their order and put comments on the generated css to indicate that it comes from shortcuts?

**Comment by chu121su12** [comment]
> The output results of sorting in alphabetical order are indeed relatively good-looking, but they ignore the issue of class order coverage, which may cause some hidden dangers of styles being overwritten and not taking effect.

It is the consequence of css using classes. Consider this example with 2 divs:

```html
<div class="bg-red bg-blue">main article</div>
<!-- ... later in html -->
<div class="bg-blue bg-red">alert with red background</div>
```

How should the css got generated? With deterministic alphabetical sorting, red would always be shown and the dev can use other workaround

> Is it possible to consider that some shortcuts are not layered separately, but retain their order and put comments on the generated css to indicate that it comes from shortcuts?

this would be a welcome addition, especially in dev mode

**Comment by Simon-He95** [comment]
Indeed, it seems that we have to leave it to the developers to solve this problem themselves.

**Pull request closed without merging**
