### PR TITLE
feat(css-transform): transform apply directive

### LINKED ISSUE #531: Support for @apply tailwind operator
Hi,
Is there is a way we can reuse styles as TailwindCss does with @apply key

More: https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply

### PR DESCRIPTION
**Pull request by hannoeru**
## Summary

transform `@apply` directive using `css-tree`

close #531

## Todo
- [x] transform `@apply` directive
- [x] transform variant groups
- [x] merge utils with the same css selector
- [x] vite plugin to handle css transform
- [ ] add a new option to apply css transformers

### CODE REVIEW

**Comment by chu121su12** [comment]
Hey. I was following the previous attempt and I'd like to propose using the existing `parseToken` and leverage the built-in generator logic https://github.com/chu121su12/unocss/commit/2860b2ae9e37e412a7c3c4c3d1e9c0fd8343b579

**Comment by rubiin** [comment]
This is something I have been waiting for . Thanks a bunch. Hope it gets merged and released in next version

**Comment by hannoeru** [comment]
@chu121su12 can you open a new PR from https://github.com/chu121su12/unocss/commit/2860b2ae9e37e412a7c3c4c3d1e9c0fd8343b579 to this branch?

**Comment by chu121su12** [comment]
I just did in #635

**Comment by antfu** [comment]
Would be great if you could have a todo list in this PR to track the progress :)

**Comment by rubiin** [comment]
@antfu I see the transformer directive is not pubished on npm. Is there an ETA

**Pull request merged**
