### PR TITLE
fix(preset-web-fonts): sort weights as string using localeCompare

### PR DESCRIPTION
**Pull request by arunanshub**
Previously, the weights were converted to Number before sorting. This would lead to conversion of string to NaN.

### CODE REVIEW

**Review by zyyv — APPROVED** [review]

**Comment by zyyv** [comment]
@arunanshub  Is there any downside to using `map(Number).sort((a,b)=>a-b)`, We are missing a step to judge whether it is a number.

**Comment by zyyv** [comment]
@arunanshub I changed the code a bit, feel free to optimize it. By the way can you add a test case for bunny. Need your review.

**Comment by arunanshub** [comment]
@zyyv In [UnoCSS docs for Web fonts preset](https://unocss.dev/presets/web-fonts#fonts) we should ideally be able to selectively choose the font weights along with their italicized versions. This is currently possible using this configuration:

```ts
{
  // ...
  fonts: {
    sans: 'Roboto',
    mono: ['Fira Mono:400,700i'],
  }
}
```

However, this method is sub-optimal. It is cleaner if we specify the weights like this:

```ts
{
  // ...
  fonts: {
    sans: 'Roboto',
    mono: {
      name: 'Fira Code',
      weights: [400, '700i'],
    },
  }
}
```

However, the current weight sorting function converts all the weight values to numbers, which converts the italicized weights to NaN.

**Comment by zyyv** [comment]
I see, I will revert my changes. Thank you for your guide.

**Comment by arunanshub** [comment]
> @arunanshub I changed the code a bit, feel free to optimize it. By the way can you add a test case for bunny. Need your review.

@zyyv The removal of italicized font weights undermines the objectives of the pull request. Our intention is to sort all font weights, **including** the italicized versions.

**Comment by zyyv** [comment]
I didn't know the weight would carry the italics, thanks again.

**Review by zyyv — APPROVED** [review]

**Pull request merged**
