### PR TITLE
fix(vscode): registerRoot calling

### PR DESCRIPTION
**Pull request by Thehrz**
In #2979, `registerRoot` was placed in the callback of the reload command, which required us to run the reload command in v0.55.1 in order to load the context. This may lead some users to think that the unocss vscode extension is not working.
This PR rolled back the behavior before v0.55.1.

### CODE REVIEW

**Comment by KraXen72** [comment]
please also check, if this fixes files with `/* @unocss-include */` not loading. as you said, i have to run reload unocss command, to load the extension, but i also have to manually remove and add this for unocss to register the files. would be great if it was fixed in one pr!

**Comment by Thehrz** [comment]
> please also check, if this fixes files with `/* @unocss-include */` not loading. as you said, i have to run reload unocss command, to load the extension, but i also have to manually remove and add this for unocss to register the files. would be great if it was fixed in one pr!

Hi, I checked the `@unocss-include` magic comment and it seems to work, can you please describe more? Or you can open a new issue.

**Comment by KraXen72** [comment]
sorry, i tested it and it works now. i was using the svelte-scoped preset which does not have config hmr, so it wasn't working. but with normal unocss/vite, it works. thanks.

**Comment by Thehrz** [comment]
fixed in #3005, close it.

**Pull request closed without merging**
