### PR TITLE
feat(shared-integration): add skip magic comment

### LINKED ISSUE #2761: Add new magic comment to skip some code for extract utilities
### Clear and concise description of the problem

When Uno extracts `utilities`, it only extracts the full amount. `@unocss-ignore` can't do something when we have a part of the code that we don't want to be extracted by Uno or transformed by the `transformer`.

### Suggested solution

I suggest add two new magic comments to skip any code between them, like `@unocss-skip-start` `@unocss-skip-end`.

### Usage: 

```vue
<script setup lang="ts">

// ...
// @unocss-skip-start
cosnt testBtnString = '<button class="px-4 py-2 rounded bg-red">test</button>'
// @unocss-skip-end

// ...
</script>
```

Uno will not extract `px-4 py-2 rounded bg-red` in tokens.

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by zyyv**
close #2761 

This PR change: 
- add `@unocss-skip-start` (A) &  `@unocss-skip-end` (B) magic comments.
- In `extract` or `transform` step, will ignore some code that between A and B.

### CODE REVIEW

**Comment by antfu** [comment]
Can you add to the docs as well? Thanks

**Comment by zyyv** [comment]
I will send a new PR about transformer that it will not transform the raw code when meet those magic comment.

**Comment by jojojojojoj5564656465465** [comment]
I tried `text-(xl hover:red slate-300) `but it's not working 

i did a shortcut and i can do `text-[slate-300,md:hover:slate-200]`

why i can't use parenthesis ?
```js

[
			/^(font|bg|border|stroke|outline|underline|ring|divide|text)-\[(.*)\]$/,
			([, category, stringElement]) => {
				const categories = [
					'font',
					'bg',
					'border',
					'stroke',
					'outline',
					'text',
					'ring',
					'divide',
					'underline'
				] as const
				const mediaQuery = ['sm', 'md', 'lg', 'xl', '2xl'] as const
				type Category = typeof categories[number]
				type MediaQuery = typeof mediaQuery[number]
				const rulesForBrakets: Record<'open' | 'close', string> = {
					open: '[',
					close: ']'
				}

				if (!categories.includes(category as Category)) {
					throw new Error(`category in not in unocss list config=> ${category}`)
				}

				const removeSpaceInString = (string: string): string => {
					return string.trim().replace(/,+/g, ' ').replace(/\s+/g, ',').replace(/\|/g, ',')
				}

				function splitString(str: string): Set<string> {
					const result = new Set<string>()
					let currentElement = ''
					let parenthesesCount = true

					for (const char of removeSpaceInString(str)) {
						if (char === rulesForBrakets.open) {
							parenthesesCount = false
						} else if (char === rulesForBrakets.close) {
							parenthesesCount = true
						}
						if (char === ',' && parenthesesCount === true) {
							result.add(currentElement.toLowerCase().trim())
							currentElement = ''
						} else {
							currentElement += char.trim()
						}
					}
					if (currentElement.trim() !== '') {
						result.add(currentElement.toLowerCase().trim())
					}
					return result
				}

				const regexAtribuffy = new RegExp(`([^:]+):\\${rulesForBrakets.open}([^\\]]+)\\${rulesForBrakets.close}$`)
				const mycustomSet = new Set<string>()

				for (const v of splitString(stringElement)) {
					if (v.includes(':')) {
						if (v.match(regexAtribuffy)) {
							const match = v.match(regexAtribuffy)

							if (match) {
								const [, md, rest] = match
								if (!mediaQuery.includes(md as MediaQuery)) {
									throw new Error('bad media querie')
								}
								const [breakpoint] = md.trim().split(':')

								for (const e of rest.split(',')) {
									if (e.includes(':')) {
										const index: number = e.lastIndexOf(':')
										const state = e.slice(0, index)
										const css = e.slice(index + 1)
										const result = `${breakpoint}:${state}:${category}-${css.trim()}`
										mycustomSet.add(result)
									} else {
										mycustomSet.add(`${breakpoint}:${category}-${e.trim()}`)
									}
								}
							}
						} else {
							const index = v.lastIndexOf(':')
							const breakpointORstate = v.slice(0, index)
							const css = v.slice(index + 1)
							const value = `${breakpointORstate}:${category}-${css.trim()}`
							mycustomSet.add(value.trim())
						}
					} else {
						mycustomSet.add(`${category}-${v.trim()}`)
					}
				}
				return Array.from(mycustomSet).join(' ')
			}
		],
		
		
```

**Comment by jojojojojoj5564656465465** [comment]
text-[slate-300,md:[hover:slate-200,red]] is working too

**Comment by zyyv** [comment]
> text-[slate-300,md:[hover:slate-200,red]] is working too

Sorry, I just saw this comment now. If you still have problems, please open a new issue.

**Pull request merged**
