### PR TITLE
docs: update community.md with new animation library

### PR DESCRIPTION
**Pull request by whatnickcodes**
[Tailwind Motion](https://rombo.co/tailwind/) by [RomboHQ](https://rombo.co/tailwind/) is an MIT licensed and open-source animation Tailwind plugin that has a ton of features via a declarative syntax. You can build highly complex animations with simple class bases and presets.

This preset is a full 100% port of that codebase.

Based off other existing animation presets, this one appears to offer the best animation options for developers as of now.

### CODE REVIEW

**Comment by zyyv** [comment]
@whatnickcodes Awesome 🤩
BTW, do you want to put it into the [community organization](https://github.com/unpreset)? I would like to invite you.

**Review by userquin — APPROVED** [review]
🤩

**Comment by whatnickcodes** [comment]
Thanks all! I have not done this type of coding or open source for a while. Excited to get this out there.

@zyyv Happy to add to that repo there if you invite. I think I can do as a template without having to change much. I plan to try and support this repo for near future.

Side note: I have a very UnoCSS heavy side project in the works (which this is for). It seems the UnoCSS discord does not get much love right now. Is there any place you all recommend for sharing/connecting with UnoCSS minded peeps for feedback?

**Comment by zyyv** [comment]
@whatnickcodes I have sent you an invitation, you can try to transfer this repo to the organization.

You can share your repository on the discord [antfu share channel](https://discord.com/channels/937808017016119440/986467380672741386), or on social platforms such as [bluesky](https://bsky.app/) or X

**Pull request merged**
