### PR TITLE
refactor(preset-attributify): improve ternary extraction

### LINKED ISSUE #1915: about dynamic attributify mode
Hello guys,

I have a class need to use attributify mode,

`pos="!fixed"` it's working

`pos={isSideFixed ? '!fixed' : 'relative'}` it's not working

How do I get the corresponding css generated in advance? using the `safelist` ?

### PR DESCRIPTION
**Pull request by sibbng**
Fixes #1915

It seems we already support this in Vue templates. This PR adds support for ternary operators in JSX and eliminates some false positives of previous ternary extraction logic.

### CODE REVIEW

**Comment by zyyv** [comment]
@sibbng Can you check your pr with this [playground](https://deploy-preview-1921--unocss.netlify.app/play/?html=DwEwlgbgUABDAOB7AzgXgN5mQZTCApgGJgAe%2BIMA-DAOQCEAZqeTTAFy0BO%2BANgIYAXSPhoBfWAhQAVfMgEYsuAsTIVq9AfhICAtNxCsONTdp2a%2BPMVAD0APihA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&options=N4XyA)

**Comment by zyyv** [comment]
In #1915 , I am more inclined that this is a user's usage rules.

**Comment by sibbng** [comment]
> @sibbng Can you check your pr with this [playground](https://deploy-preview-1921--unocss.netlify.app/play/?html=DwEwlgbgUABDAOB7AzgXgN5mQZTCApgGJgAe%2BIMA-DAOQCEAZqeTTAFy0BO%2BANgIYAXSPhoBfWAhQAVfMgEYsuAsTIVq9AfhICAtNxCsONTdp2a%2BPMVAD0APihA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&options=N4XyA)

posTest is not a valid rule. So it's not picked up by any attributify selector.

> In #1915 , I am more inclined that this is a user's usage rules problem.

No, it's not. We already have a test for extracting ternaries from vue templates. This PR adds support for JSX.

**Comment by zyyv** [comment]
> We already have a test for extracting ternaries from vue templates

Can you guide me where is the test code?

image

Following this image, this token was not generated because it has no corresponding rule or variant

**Comment by sibbng** [comment]
> Can you guide me where is the test code?

test/preset-attributify.test.ts:22

**Comment by zyyv** [comment]
> > Can you guide me where is the test code?
> 
> test/preset-attributify.test.ts:22

https://github.com/unocss/unocss/blob/22c4e70d53870b9413399e0ed20a7fece610eaa3/test/preset-attributify.test.ts#L22

About this line, you can see UnoCSS extracted results:
https://github.com/unocss/unocss/blob/22c4e70d53870b9413399e0ed20a7fece610eaa3/test/__snapshots__/preset-attributify.test.ts.snap#L28-L34
Only `font-mono` and `font-sans` can be parsed, because we have its rules.
https://github.com/unocss/unocss/blob/22c4e70d53870b9413399e0ed20a7fece610eaa3/test/__snapshots__/preset-attributify.test.ts.snap#L199-L200

-----
In #1915, We don't have any rule or variant about `pos`

**Comment by sibbng** [comment]
> In https://github.com/unocss/unocss/issues/1915, We don't have any rule or variant about pos

`pos` is shorthand for `position`
https://github.com/unocss/unocss/blob/22c4e70d53870b9413399e0ed20a7fece610eaa3/packages/preset-mini/src/_rules/position.ts#L5-L9

> About this line, you can see UnoCSS extracted results:

This is exactly what I called false positives. In this case, they will make it to output since there are no matching rules as you said. But, what if the variables we used in ternaries are has matching rules? e.g:

```ts
<div
  :text="xl ? '5xl' : 'base'"
/>
```
- [Deploy preview playground](https://uno.antfu.me/play/?html=DwEwlgbgUABDBcAXApgD0QXgESoDYwH4YByAVj2IRICMBDAZ2WKygHoA%2BKIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFZs9hIw0HQAXHAA2v6ocLj2IBiRejAYUAlQ-AC0gVDBoVB6sgGWQSE%2BIZYAlIhUcXBOjHB0cAC8cFUAdFKY9XFSuHTw8s4wrR1RALr9qIPDcLTtcAD0ADxRADoA7l1TANRRAHoAfFMAVAD84Zc%2B1z5b29kH1W0xegBEUz5d%2B7fXXWqV02l32d3CgKu4Kin2%2Bx1h%2B2qMK%2B-3Cm1wAB9IfcAUDLsi4UcEUjYZdqki1LDwdjqvsVqQQHRZo1miB7DAJAALZnbTnAJpwHxsjmc5a0LpWDASHx0cl1BoNCYtLq0MBOYIYIXsrlRABMU3I%2Bj01WZqHF6uGYlwmEsywADKbOtJ4Oy2MthTqAIwzBVxPg%2BV1QdptDp6CQW0xwDEYuCB4Oh8P2EwAOUSGGNTtwvFwXAwjvm8CaWHgHQ9nKiAGYfb6WcWunQ1cAYD49Ppql0sNAAKLBTk%2BYDtE6LehjOhdMBcOh9gAGUQAJAhA2oAH5tD4L4BqL7T8n552LbycktwMtRAAs1d97FIR-rjebreNHe7vf7g%2BHdFH48nM-ni9YUArmuG5blMO4mjWmZ0BATRdE4EC%2BKMLiysyajMrQMBcBkH6jv0aiyGoBpUFAzj0JEUT9DCEiTqEIDZCRTTFIgTrwVAKS0GgraEVQRGoFO0AcjwETynEYY0To2T8bA1EwHoKRpGU2ROKQcAKTA2TQPYuCkBgcCchAABu6ThGp2RpPYThmKg%2BFUCICjCRRDR2YwygQD41QlHIojMABnA8Hw-DuZ5zkwJI0h%2BMydASBZyRwJ6XS6p5cxoLgKRHjAYARCsKz0CA9acisVlxGoHk8UgJVIEAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)
- [main branch Playground](https://uno.antfu.me/play/?html=DwEwlgbgUABDBcAXApgD0QXgESoDYwH4YByAVj2IRICMBDAZ2WKygHoA%2BKIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFZs9hIw0HQAXHAA2v6ocLj2IBiRejAYUAlQ-AC0gVDBoVB6sgGWQSE%2BIZYAlIhUcXBOjHB0cAC8cFUAdFKY9XFSuHTw8s4wrR1RALr9qIPDcLTtcAD0ADxRADoA7l1TANRRAHoAfFMAVAD84Zc%2B1z5b29kH1W0xegBEUz5d%2B7fXXWqV02l32d3CgKu4Kin2%2Bx1h%2B2qMK%2B-3Cm1wAB9IfcAUDLsi4UcEUjYZdqki1LDwdjqvsVqQQHRZo1miB7DAJAALZnbTnAJpwHxsjmc5a0LpWDASHx0cl1BoNCYtLq0MBOYIYIXsrlRABMU3I%2Bj01WZqHF6uGYlwmEsywADKbOtJ4Oy2MthTqAIwzBVxPg%2BV1QdptDp6CQW0xwDEYuCB4Oh8P2EwAOUSGGNTtwvFwXAwjvm8CaWHgHQ9nKiAGYfb6WcWunQ1cAYD49Ppql0sNAAKLBTk%2BYDtE6LehjOhdMBcOh9gAGUQAJAhA2oAH5tD4L4BqL7T8n552LbycktwMtRAAs1d97FIR-rjebreNHe7vf7g%2BHdFH48nM-ni9YUArmuG5blMO4mjWmZ0BATRdE4EC%2BKMLiysyajMrQMBcBkH6jv0aiyGoBpUFAzj0JEUT9DCEiTqEIDZCRTTFIgTrwVAKS0GgraEVQRGoFO0AcjwETynEYY0To2T8bA1EwHoKRpGU2ROKQcAKTA2TQPYuCkBgcCchAABu6ThGp2RpPYThmKg%2BFUCICjCRRDR2YwygQD41QlHIojMABnA8Hw-DuZ5zkwJI0h%2BMydASBZyRwJ6XS6p5cxoLgKRHjAYARCsKz0CA9acisVlxGoHk8UgJVIEAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

As you can see from the output an unnecessary selector `[text~="xl"]` is generated in main branch.

This PR makes sure, only the quoted strings in the true or false side of the ternary are extracted. Both for vue and JSX.

**Comment by zyyv** [comment]
I'm so sorry, and thanks for you answer, you are right. I never use `pos` this shorthand, i forgot it. 😅

**Review by zyyv — APPROVED** [review]

**Comment by Handpear** [comment]
Thanks for this PR, are there any plans for new releases in the near future?

**Pull request merged**
