### PR TITLE
feat(preset-web-fonts): try using local fonts

### PR DESCRIPTION
**Pull request by chris-zhu**
As the mdn [docs](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src) said, if we use webFonts inline import, try using `local` first.

### CODE REVIEW

**Review by sudongyuer — CHANGES_REQUESTED** [review]
supports these font-family names
  `font-family: myFirstFont`
  `font-family: "myFirstFont"`
  `font-family: 'myFirstFont'`

**Review by sudongyuer — APPROVED** [review]

**Comment by antfu** [comment]
I am not so sure, it's this the responsibility of Google Fonts? If they didn't do this probably there are some reasons.

**Comment by chris-zhu** [comment]
> I am not so sure, it's this the responsibility of Google Fonts? If they didn't do this probably there are some reasons.

I'll keep watching and continue to investigate why.

**Comment by chris-zhu** [comment]
I will close this PR, details in https://github.com/google/fonts/issues/5418#issuecomment-1281724382.

**Pull request closed without merging**
