### PR TITLE
feat: source map support for transformers

### PR DESCRIPTION
**Pull request by hannoeru**

### CODE REVIEW

**Comment by antfu** [comment]
I think the core (aim to be lightweight) should not deps on `magic-string` but only  the transformers.

**Comment by hannoeru** [comment]
core package only uses types from `magic-string`, `magic-string` is only install as dependencies on vite package.

**Comment by antfu** [comment]
@hannoeru @chu121su12 Can you help resolve this conflict? 😅

**Comment by antfu** [comment]
Thanks!

**Pull request merged**
