### PR TITLE
feat(vscode): configure multiple subdirs

### PR DESCRIPTION
**Pull request by MellKam**
https://github.com/unocss/unocss/issues/1764

now you can pass array to unocss.root
```json
"unocss.root": ["apps/a", "apps/b"]
```
or just a string as before 
```json
"unocss.root": "apps/c"
```

### CODE REVIEW

**Comment by MellKam** [comment]
now you can pass array to unocss.root
```json
"unocss.root": ["apps/a", "apps/b"]
```
or just a string as before 
```json
"unocss.root": "apps/c"
```

**Comment by tobiasdalhof** [comment]
Why not use the first unocss config found when searching the file tree in reverse for convenience?

**Comment by MellKam** [comment]
> Why not use the first unocss config found when searching the file tree in reverse for convenience?

But what if I want to use more than one config in my project? For example I have uikit and frontend app in one monorepo.

**Comment by tobiasdalhof** [comment]
> UPD: Maybe I misunderstood you. Do you want to search from the currently open file up the directory tree to the first configurator found?

Yes, that's what I ment

**Review by antfu — APPROVED** [review]

**Pull request merged**
