### PR TITLE
fix(cli): load config twice

### LINKED ISSUE #1689: `@unocss/cli` warn about duplication of preset
image

To reproduce, install `@unocss/cli`, create `uno.config.js` and add any preset then run the CLI. Warning message is always appeared in screen.

After some digging, I think `loader.load()` doesn't work correctly. It's duplicate entries of `presets` array instead of "merge" or something and that cause the problem.

https://github.com/unocss/unocss/blob/76b883f3d412b61be85f35b08ebc5f616abef818/packages/config/src/index.ts#L57

### PR DESCRIPTION
**Pull request by avxit**
This should fix #1689 .

### CODE REVIEW

**Comment by sudongyuer** [comment]
test failed

**Review by chris-zhu — APPROVED** [review]

**Comment by avxit** [comment]
> test failed

Yeah..., wrong `cwd` and the test failed. I don't know whether should I modified `createContext` to accept `cwd` or not?

**Comment by chris-zhu** [comment]
> 

Yes, i agree with you. But it looks a bit ...

**Comment by avxit** [comment]
> Yes, i agree with you. But it looks a bit ...

I've updated the PR with `ctx.updateRoot` to update correct `cwd`.

**Review by antfu — APPROVED** [review]

**Pull request merged**
