### PR TITLE
feat(preset-wind): add `svh`, `lvh` and `dvh` values to default theme

### PR DESCRIPTION
**Pull request by navorite**
this adds `svh`, `lvh` and `dvh` as default values to `height`, `min-height`, `max-height` rules to improve compatibility with TailwindCSS v3.4.0

Tailwind Ref: https://tailwindcss.com/blog/tailwindcss-v3-4#dynamic-viewport-units

### CODE REVIEW

**Comment by chu121su12** [comment]
vh units are already [supported](https://unocss.dev/play/?html=BYWgjADBAmBuwCgg&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4XyA). Maybe we can adjust its usage in the size rules?

**Comment by navorite** [comment]
> vh units are already [supported](https://unocss.dev/play/?html=BYWgjADBAmBuwCgg&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4XyA). Maybe we can adjust its usage in the size rules?

This adds the **default rules** of dynamic viewport height, not the values (which as you mentioned already exist), meaning `min-height-dvh` will generate `min-height: 100dvh`, which Tailwind just added in v3.4.0. 

I think it's more reasonable to leave it in static rules because it is a static rule (does not have any dynamic value in it). It is just for Tailwind compatibility. For pure values like `min-h-100dvh`, support already exists so there is no reason to add that in sizes.

**Comment by chu121su12** [comment]
Then I think it is better to add this to the preset-wind instead

**Comment by navorite** [comment]
> Then I think it is better to add this to the preset-wind instead

Done. I think that makes more sense.

**Review by antfu — APPROVED** [review]

**Pull request merged**
