### PR TITLE
Docs/example nextjs (#1094)

### LINKED ISSUE #1094: how to use unocss with next.js?
how to use unocss with next.js?

### PR DESCRIPTION
**Pull request by Sickisonfire**
I've created an example for Nextjs with '@unocss/webpack'.

Let me know if i can improve anything!

close #1094

### CODE REVIEW

**Comment by antfu** [comment]
Can't we use `@unocss/webpack` instead of the cli? Wondering what's the blocker?

**Comment by Sickisonfire** [comment]
Oh my bad, i mistook the `uno.config.ts` way as being part of `@unocss/webpack`. 
Let me try to refactor it and use `@unocss/webpack` for real this time :smile:

**Comment by Sickisonfire** [comment]
I've updated the example. It's using the webpack plugin now. Compared to the cli approach there is one downside though. For style changes to be displayed, one has to manually refresh the page.

**Comment by Songkeys** [comment]
The inconsistent behaviour while developing leads me here.

> turning off webpacks caching solves the reloading issue.

Could you please give us a config snippet? Thank you.

Also, is it possible to use a swc compiler since next.js [supports it](https://nextjs.org/docs/advanced-features/compiler#why-swc) now?

**Comment by Sickisonfire** [comment]
```diff
const nextConfig = {
  reactStrictMode: true,
  webpack: (config) => {
+    config.cache = false
    config.plugins.push(
      UnoCSS({
        //...
      })
    )
    return config
  }
}
```
Just add `config.cache = false` to your next.config.js like above.

I'm not quite familiar with swc but as i understand it swc does just the compiling for next. Webpack is still used for bundling and that's where unocss hooks in as a webpack plugin.

**Comment by Songkeys** [comment]
> Just add config.cache = false to your next.config.js like above.

Adding this config actually hangs my page on loading the page request. There's no error. The example in this repo can reproduce it.

**Comment by Sickisonfire** [comment]
> Adding this config actually hangs my page on loading the page request. There's no error. The example in this repo can reproduce it.

That's strange. I have no issues on my end. Have you tried deleting the `.next` folder? I've found that deleting it helped in certain cases.

**Pull request merged**
