### PR TITLE
feat(playground): add custom css panel

### LINKED ISSUE #2181: ✨ Allow writing plain CSS in playground
### Clear and concise description of the problem

We don't have an editor to write raw CSS in the playground for providing a reproducible examples. We do have [preflight](https://github.com/unocss/unocss#preflight) option but providing separate CSS panel is more convenient just like tailwind:
image
reproducible examples

### Suggested solution

Provide a separate CSS panel just like "Ouput CSS"

### Alternative

Using Tailwind Playground for now

### Additional context

N/A

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by zyyv**
close #2181

You can simply preview it.
image
image

### CODE REVIEW

**Comment by zyyv** [comment]
The url length is really long.
image

**Comment by antfu** [comment]
Can we have tabs instead? A toggle might be too unnoticeable. Like

`> | Output CSS | Custom CSS |  <actions>`

**Comment by zyyv** [comment]
> Can we have tabs instead? A toggle might be too unnoticeable. Like
> 
> `> | Output CSS | Custom CSS | <actions>`

Can use `Output | Custom` instead? The title is too long and not friendly to small screens.

**Comment by antfu** [comment]
Or maybe just one more panel?

**Comment by zyyv** [comment]
Added new change: 
- [x] Add `Custom CSS` panel before `Output CSS` panel.
- [x] Strip the `<Headerbar />` from the `<HTMLpanel />`
- [x] Fixed get the `splutpanes` element height is `undefined`

**Comment by userquin** [comment]
> The url length is really long. image

Should not exceed 2048 characters, but (I0ve never tested it :sweat_smile: ):
- Google Chrome: allows the maximum length of the URL to be of the size 2MB (2,097,152 characters).
- Mozilla Firefox: the length of the URL can be unlimited but practically after 65,536 characters the location bar no longer displays the URL.
- Edge: allows the URL length to be a maximum of 2083 characters but not more than 2048 characters in the path portion of the URL.
 - Opera: allows the URL length to be unlimited.
 - Safari: maximum length of URL in Safari is 80000 characters after crossing this limit the page displays an error.

**Comment by zyyv** [comment]
> > The url length is really long. image
> 
> Should not exceed 2048 characters, but (I've never tested it 😅 ):
> 
> * Google Chrome: allows the maximum length of the URL to be of the size 2MB (2,097,152 characters).
> * Mozilla Firefox: the length of the URL can be unlimited but practically after 65,536 characters the location bar no longer displays the URL.
> * Edge: allows the URL length to be a maximum of 2083 characters but not more than 2048 characters in the path portion of the URL. New version should have the same limit Chrome has (Chromiun)
> * Opera: allows the URL length to be unlimited.
> * Safari: maximum length of URL in Safari is 80000 characters after crossing this limit the page displays an error.

Sometimes, i want to share some unocss playground demo on Elk or twitter, because of that length is too long, i have to abandoned it.😅

**Pull request merged**
