### PR TITLE
feat(nuxt): watch unocss config file

### PR DESCRIPTION
**Pull request by HigherOrderLogic**
Let the Nuxt dev server know to restart when the config files are changed.

### CODE REVIEW

**Comment by zyyv** [comment]
Why we need this changes to restart nuxt dev server?

**Comment by HigherOrderLogic** [comment]
I'm on Windows and when running Nuxt dev server, changing the `uno.config.ts` file doesn't apply change in HMR. Because of that I think the server need a full reload to apply the new config.

**Comment by zyyv** [comment]
> I'm on Windows and when running Nuxt dev server, changing the `uno.config.ts` file doesn't apply change in HMR. Because of that I think the server need a full reload to apply the new config.

I tested it on my Mac and it works fine. I can't help you on Windows. Can you create an issue to report the problem, preferably with a minimal reproduction, maybe more people in the community can help us verify it?

**Comment by zyyv** [comment]
Also closed due to long period of inactivity. If you have any updates, please feel free to reopen it.

**Pull request closed without merging**
