### PR TITLE
feat(preset-mini,preset-wind): add basic opacity theme

### PR DESCRIPTION
**Pull request by chu121su12**
- add in base `opacity-x`
- add in rules `x-opacity-y`
- theme opacity in `colorParser`

### CODE REVIEW

**Comment by antfu** [comment]
What would you expect the use case of this?

**Comment by chu121su12** [comment]
I did this to add theme for opacity for consistency. I'm actually unsure for the use case, hence this is a separate PR.

One I can think of is maybe for pseudo styling. Otherwise, feel free to close this.

**Comment by antfu** [comment]
I don't mind having it, just not sure if it's something that actually have ppl using it

**Comment by chu121su12** [comment]
Maybe we can reintroduce this when there's a demand for it

**Pull request closed without merging**
